name: Run Python Script and Save Artifact

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  push:  # Optional: Trigger on pushes to the repo
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # or your desired version

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Run the Python script
      - name: Run Python script
        run: python main.py

      # Upload the generated file as an artifact
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: output-files
          path: results/
