name: Run Python Script with Custom Fields

on:
  workflow_dispatch:
    inputs:
      script_argument1:
        description: 'Capability to be checked'
        required: true
        type: choice
        options:
          - cap-bet-building-and-placement
          - cap-search
          - cap-same-game-multi
          - cap-bet-overlay
          - cap-account-session-and-wallet-proxy
          - cap-bet-lifecycle
        default: cap-bet-building-and-placement

      script_argument2:
        description: 'Number of days back to search for PRs'
        required: false
        default: '15'

      script_argument3:
        description: 'Status of PRs to search for (open/closed/open_draft/all)'
        required: true
        type: choice
        options:
          - open
          - closed
          - open_draft
          - all
        default: open

      script_argument4:
        description: 'Type of date of PR to look at (created/updated)'
        required: true
        type: choice
        options:
          - created
          - updated
        default: updated

      email:
        description: 'Email of the user'
        required: true
        default: ''

      name:
        description: 'Name of the user'
        required: true
        default: ''

  repository_dispatch:
    types: [run-python-script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # or your desired version

      - name: Run Python script with arguments and secret
        env:
          SECRET_KEY: ${{ secrets.KEY1_REPO_PERMS_ONLY }} # Pass the secret as an environment variable
        run: |
          python main.py "${{ github.event.inputs.script_argument1 }}" \
                         "${{ github.event.inputs.script_argument2 }}" \
                         "${{ github.event.inputs.script_argument3 }}" \
                         "${{ github.event.inputs.script_argument4 }}" \
                         "${{ github.event.inputs.email }}" \
                         "${{ github.event.inputs.name }}"
