name: Run Python Script with Custom Fields

on:
  workflow_dispatch:
    inputs:
      script_argument1:
        description: 'Capability to be checked' # Describe the dropdown field
        required: true # Make the field mandatory
        type: choice # Specify this as a dropdown
        options: # Define the dropdown options
          - cap-bet-building-and-placement
          - cap-search
          - cap-same-game-multi
          - cap-bet-overlay
          - cap-account-session-and-wallet-proxy
          - cap-bet-lifecycle
        default: cap-bet-building-and-placement # Set the default value
        
      script_argument2:
        description: 'Number of days back to search for PRs'
        required: false
        default: '15'

      script_argument3:
        description: 'Status of PRs to search for (open/closed/open_draft/all)' # Describe the dropdown field
        required: true # Make the field mandatory
        type: choice # Specify this as a dropdown
        options: # Define the dropdown options
          - open
          - closed
          - open_draft
          - all
        default: open # Set the default value

      script_argument4:
        description: 'Type of date of PR to look at (created/updated)' # Describe the dropdown field
        required: true # Make the field mandatory
        type: choice # Specify this as a dropdown
        options: # Define the dropdown options
          - created
          - updated
        default: updated # Set the default value

  repository_dispatch:
    types: [run-python-script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # or your desired version

      - name: Run Python script with arguments
        run: |
          python main.py "${{ github.event.inputs.script_argument1 }}" "${{ github.event.inputs.script_argument2 }}" "${{ github.event.inputs.script_argument3 }}" "${{ github.event.inputs.script_argument4 }}"
