name: Run Python Script with Custom Fields

on:
  workflow_dispatch:
    inputs:
      script_argument1:
        description: 'First argument for the Python script' # Describe what this argument is
        required: true # Set to true to ensure it's provided
        default: 'default_value1' # Provide a default if applicable
      script_argument2:
        description: 'Second argument for the Python script'
        required: false
        default: 'default_value2'

  repository_dispatch:
    types: [run-python-script]

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' # or your desired version

      - name: Run Python script with arguments
        run: |
          python main.py "${{ github.event.inputs.script_argument1 }}" "${{ github.event.inputs.script_argument2 }}"
